language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - nosetests -s -v
  - pyflakes Mollie/

deploy:
  provider: pypi
  user: "MolopsDeploy"
  password:
    secure: "tX5VvpXIj7Afm9slPgCeSwelTxRnWPGfQcglTw92PoHlYeVbgiesEaH2uxIVS3cDeHWTHY4JsT/P2Juu6kZzga+Cb8thUND4JRYeUd1vizJblbeb5hgBRlQ8W/7x6k3j+Eh0I62HW7VDIiyM4uEBhigai4eJyuCK73pFmRmNfxw="